### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by captn3m0** [captn3m0/disable-web-fonts#1]
There should be a whitelist, stored as configuration options in localStorage; this would be matched against for every request that is intercepted. If the request referrer's domain is in the whitelist, then we skip the request in question (ie its not blocked).

Websites that would need this whitelist include `github.com`.

**Comment by jitendravyas** [comment]
Any progress on whilelist?

**Comment by captn3m0** [comment]
No, I didn't know anyone was even using this.

**Comment by jitendravyas** [comment]
I have installed it today. I found this when I was searching for ways to disable web fonts in browser. 

I liked this plugin. I wish Whitelist and localfont blocking feature ( which is opposite to this)

Thanks for the plugin

**Comment by captn3m0** [comment]
When you say `localfont blocking feature`, do you mean blocking fonts that are served from the same domain?

**Comment by jitendravyas** [comment]
no. i actually want this feature https://code.google.com/p/chromium/issues/detail?id=472136 as a plugin.

**Comment by captn3m0** [comment]
That would be an entirely different plugin, I think. 

If you'd like to work on it, [this is a good API to start with](https://developer.chrome.com/extensions/fontSettings#method-getFontList).

**Comment by captn3m0** [comment]
Closing this.

I've added this to my [ideas repo](https://github.com/captn3m0/ideas#disable-local-fonts-extension) if anyone wants to work on this.
